name: Emova Scraper

on:
  schedule:
    - cron: '*/15 * * * *'  # Cada 15 minutos
  workflow_dispatch:         # Permite ejecutarlo manualmente desde GitHub

jobs:
  scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar scraper
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GCBA_CLIENT_ID: ${{ secrets.GCBA_CLIENT_ID }}
          GCBA_CLIENT_SECRET: ${{ secrets.GCBA_CLIENT_SECRET }}
        run: python scraper.py
