name: Ejecutar Scraper de Subtes

on:
  schedule:
    # Se ejecuta exactamente cada 40 minutos de forma continua
    - cron: '*/40 * * * *'
    - cron: '20-59/40 * * * *'
  workflow_dispatch: # Esto te permite activar el script manualmente con un botón cuando quieras

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código del repositorio
      uses: actions/checkout@v4

    - name: Configurar Python en el servidor
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar librerías necesarias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar el script verificador
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python scraper.py
